Add validation YAML script to verify YAML files
To run the script:

```
ruby verify_yaml.rb
```

A sample output is:
```
$ ruby verify_yaml.rb
YAML file './acrobot.yaml' valid!
YAML file './data/abbrev.yaml' valid!
YAML file './data/draft.yaml' valid!
```

In case of failure, the script will point out the non-valid YAML file
and the reason:

```
$ ruby verify_yaml.rb
>> YAML file './acrobot.yaml' is not valid!
>> Error: (./acrobot.yaml): could not find expected ':' while scanning a simple key at line 8 column 1
YAML file './data/abbrev.yaml' valid!
YAML file './data/draft.yaml' valid!
```

In addition, the script will terminate with a non-zero exit code.